
package com.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 16 17:22:06 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "addCountry", namespace = "http://service.webservice.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addCountry", namespace = "http://service.webservice.com/")

public class AddCountry {

    @XmlElement(name = "country")
    private java.lang.String country;

    public java.lang.String getCountry() {
        return this.country;
    }

    public void setCountry(java.lang.String newCountry)  {
        this.country = newCountry;
    }

}

