
package com.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 15 16:43:40 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "addPoliticianResponse", namespace = "http://service.webservice.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addPoliticianResponse", namespace = "http://service.webservice.com/")

public class AddPoliticianResponse {

    @XmlElement(name = "politician")
    private int politician;

    public int getPolitician() {
        return this.politician;
    }

    public void setPolitician(int newPolitician)  {
        this.politician = newPolitician;
    }

}

