
package com.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Mon Apr 12 16:20:07 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getAllPoliticians", namespace = "http://service.webservice.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllPoliticians", namespace = "http://service.webservice.com/")

public class GetAllPoliticians {

    @XmlElement(name = "arg0")
    private com.webservice.model.Country arg0;

    public com.webservice.model.Country getArg0() {
        return this.arg0;
    }

    public void setArg0(com.webservice.model.Country newArg0)  {
        this.arg0 = newArg0;
    }

}

