
package com.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Mon Apr 12 16:20:07 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getAllPoliticiansResponse", namespace = "http://service.webservice.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllPoliticiansResponse", namespace = "http://service.webservice.com/")

public class GetAllPoliticiansResponse {

    @XmlElement(name = "politician")
    private java.util.ArrayList<com.webservice.model.Politician> politician;

    public java.util.ArrayList<com.webservice.model.Politician> getPolitician() {
        return this.politician;
    }

    public void setPolitician(java.util.ArrayList<com.webservice.model.Politician> newPolitician)  {
        this.politician = newPolitician;
    }

}

