
package com.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Mon Apr 12 16:20:07 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getCountryResponse", namespace = "http://service.webservice.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCountryResponse", namespace = "http://service.webservice.com/")

public class GetCountryResponse {

    @XmlElement(name = "country")
    private com.webservice.model.Country country;

    public com.webservice.model.Country getCountry() {
        return this.country;
    }

    public void setCountry(com.webservice.model.Country newCountry)  {
        this.country = newCountry;
    }

}

