
package com.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 16 17:22:06 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getPoliticianByCountryResponse", namespace = "http://service.webservice.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPoliticianByCountryResponse", namespace = "http://service.webservice.com/")

public class GetPoliticianByCountryResponse {

    @XmlElement(name = "politician")
    private java.lang.String politician;

    public java.lang.String getPolitician() {
        return this.politician;
    }

    public void setPolitician(java.lang.String newPolitician)  {
        this.politician = newPolitician;
    }

}
   
